name: Test MKL
# Workflow has two modes: assert and report
# Push and pull request run in assert mode.
# Schedule and dispatch run in report mode.
on:
  push:
    paths-ignore:
      - "**.md"
    tags-ignore:
      - v**
  pull_request:
    branches:
      - main
      - develop*
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  test:
    name: Test MKL
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fortran with MKL
        id: setup-fortran
        uses: ./
        with:
          compiler: intel
          version: 2025.0.0
          extra_components: intel.oneapi.win.mkl.devel

      - name: List the installed directories (recursively)
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Directory "${{ env.ONEAPI_ROOT }}"
